apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: order-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: thanhtuanh/order-service:latest # Passe ggf. auf deinen DockerHub-Namen an!
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/demo
            - name: SPRING_DATASOURCE_USERNAME
              value: demo
            - name: SPRING_DATASOURCE_PASSWORD
              value: demopw