apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2 # Zwei Instanzen für Ausfallsicherheit
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: thanhtuanh/user-service:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env: 
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/users
            - name: SPRING_DATASOURCE_USERNAME
              value: demo
            - name: SPRING_DATASOURCE_PASSWORD
              value: demopw
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080